### ISSUE TITLE
package by feature

### ISSUE THREAD

**Issue by athkalia** [ImangazalievM/Bubbble#2]
Had a look at the project, looks great!

You may want to package things by feature, as packing by type doesn't scale well. 
So for example this means that all the presenters won't be together, but you'll have everything related to a specific feature/screen in one folder. Plenty of articles on it on the web if you wanna investigate further.

cheers,
Sakis

**Comment by ImangazalievM** [comment]
Hello! Thanks for the feedback. Package by layer more uncomfortablefor me)

**Comment by ImangazalievM** [comment]
Hello! Thanks for the feedback. Unfortunately, package classes by feature uncomfortable for me)

**Comment by athkalia** [comment]
sure, just a suggestion : )

**Comment by ImangazalievM** [comment]
Hello @athkalia. So you were right, package by feature really more better. I'll change packages structure soon.
